JPERF-729: Create a way to configure Jira admin user password during database setup
atlassian/infrastructure pull request #107
Opened 2021-06-28 11:42 UTC by pczuj

# This is draft

* I didn't test if SQL is correct
    * I'd like to use code already present in #103 for that, however I'm not yet 100% sure how to do it correctly
* I believe those changes are not compatible with #103 hance I'd like to consult how I can help to reduce the conflicts and possibly contribute to the #103 with the new password overwrite feature in the new form
* I think that this may be a good opportunity to check if changes in #103 are flexible enough for new features like password overwrite in database
* The password overwrite feature could also be implemented with property `-Datlassian.recovery.password=<your-password>`. I decided to use the database setup wrapper without any good reason.

2021-06-28 13:29 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        cwdUserTableName = "jiradb.cwd_user"
Builder would contain the defaults and remove all 3 public constructors (leaving just 1 private one), unblocking API evolution.

2021-06-28 13:29 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +) : Database {
That's how `LicenseOverridingMysql` is done, so right now it's ok 👌 

But when #103 comes, the `Database` SPI will be obsolete. [`DockerMysqlServer` is just a `PreInstanceHook`](https://github.com/atlassian/infrastructure/pull/103/files#diff-7d069955c11a4da663e43af1c359b89334fd21dd349e4eb9dfc288ebd25f1c85). But it could expose callbacks to its `SshSqlClient` via its builder.

2021-06-28 13:29 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
Alternatively, the password could be [transferred via a file](https://github.com/atlassian/infrastructure/blob/release-4.18.0/src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt#L46-L57), which avoids being logged in SSH logs.

2021-06-28 13:29 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='$encodedPassword' WHERE user_name='$username';")
How does Jira know how to decode this? Do they know the salt?

2021-06-28 13:56 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +class JiraUserPasswordOverridingDatabaseTest {
#103 brings integration tests, which cover whole Jira provisioning

2021-06-28 14:56 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
I was trying to understand the rationale behind the SQL file. Is it for the diagnostics purposes to avoid logging?

I'm assuming that the DB stored encrypted passwords are safe to print for the eyes of someone who already has ssh key printed in the log as well.

2021-06-28 14:57 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='$encodedPassword' WHERE user_name='$username';")
I don't know, possibly salt is empty, but it's just mu guess

2021-06-28 15:09 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
SSH keys are not logged. JPT logs help with troubleshooting and as such they should be easy to share, without a need for pseudonymisation. So secrets (private keys, passwords, PII) should not be logged. They should be transferred via files if at all.

PS. Raised https://ecosystem.atlassian.net/browse/JPERF-746

2021-06-28 15:11 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
Logging encrypted secrets is safe only if decryption remains secret. So: https://github.com/atlassian/infrastructure/pull/107#discussion_r659786854

2021-06-28 15:23 UTC, pczuj commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +class JiraUserPasswordOverridingDatabaseTest {
Could I somehow use #103 to write a IT on top of it which I could easily test if the password is correctly replaced (select via sql client as an assert)? Maybe I could use the opportunity to actually contribute to that PR with the feature reimplemented?

2021-06-28 15:35 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
TBH I don't like when the logging is part of the class logic. I prefer to create diagnostics mechanisms at the edge of the component usage, that way I'm actually making sure that my implementation is thin enough (similar to how unit tests help model things).

I think I will create a `DiagnosticsSshSqlClient` which will store all of the sql commands in files and it will print those file paths. This will be transparent to the `Database` logic.

2021-06-28 15:35 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
Or maybe I will just skip the logging

2021-06-28 15:47 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
> Or maybe I will just skip the logging

Reason is that because the `SshSqlClient` can be overwritten in the `JiraUserPasswordOverridingDatabase`, a wrapper with diagnostics can be written in the test code if the author wants more visibility.

2021-06-29 07:29 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +class JiraUserPasswordOverridingDatabaseTest {
You could target that branch. I push it and rebase it every Friday, but if you merge a PR to it, I will preserve the changes.

2021-06-29 08:26 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
The `logger.debug` is up to you. But note that SSH layer is logging all commands anyway.

2021-06-30 08:09 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        cwdUserTableName = "jiradb.cwd_user"
Builder implemented ✅

2021-11-24 09:18 UTC, dagguh requested changes

2021-11-24 09:18 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +    fun shouldExecuteUpdateOnCwdUserTableWithEncryptedPassword_whenUnknownUserEncryptionMethod() {
```suggestion
    fun shouldUpdateEncryptedPasswordByDefault() {
```

2021-11-24 09:18 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +    fun shouldExecuteUpdateOnCwdUserTableWithEncryptedPassword_whenPlainTextSecurityUserEncryptionMethod() {
```suggestion
    fun shouldUpdatePlaintextPassword() {
```

2021-11-24 09:18 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabaseTest.kt
> +    fun shouldExecuteUpdateOnCwdUserTableWithEncryptedPassword_whenAtlassianSecurityUserEncryptionMethod() {
```suggestion
    fun shouldUpdateEncryptedPassword() {
```

2021-11-24 09:18 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> -    fun setup(ssh: SshConnection): String
This breaks the API.

- [ ] don't break the API unless absolutely necessary (requires major release cascade)

2021-11-24 09:18 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +data class JiraUserPassword(
- [ ] log new API in the changelog

2021-11-24 11:48 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> -    fun setup(ssh: SshConnection): String
Is major release a problem/effort? If not, I would not stop from making small breaking changes to improve the code

2021-11-24 11:57 UTC, wyrzyk commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> -    fun setup(ssh: SshConnection): String
The relese is only one part (the smaller one).  Customers need to adapt to the incompatible changes as well.

2021-11-24 11:59 UTC, wyrzyk commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> -    fun setup(ssh: SshConnection): String
>I would not stop from making small breaking changes to improve the code.

In most cases, you can make changes that are backward compatible.

2021-11-24 13:53 UTC, dagguh requested changes

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> +    fun performSetup(ssh: SshConnection): DatabaseSetup
Note that this is also breaking API:
[2.4.3. Do not add methods to a released public Java interface
](https://github.com/wyrzyk/java-api-design-checklist/blob/master/CHECKLIST.md#24-interfaces)

You'd have to add a default method. It's problematic in Kotlin, do you'd have to port this class to Java. E.g. we had to do that for [Scenario](https://github.com/atlassian/jira-actions/blob/release-3.16.0/src/main/java/com/atlassian/performance/tools/jiraactions/api/scenario/Scenario.java#L31-L33).

Or we could just forget the `DatabaseSetup` abstraction, because it doesn't bring new semantics/behavior, so it's a speculative abstraction.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> +    @Deprecated(message = "Use setupAndGetLocation instead", replaceWith = ReplaceWith("performSetup(ssh)"))
> setupAndGetLocation

But `setupAndGetLocation` doesn't exist.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/Database.kt
> +    @Deprecated(message = "Use setupAndGetLocation instead", replaceWith = ReplaceWith("performSetup(ssh)"))
`ReplaceWith("performSetup(ssh)")` wouldn't actually be a safe replacement, it wouldn't compile.
Instead, we'd need `ReplaceWith("performSetup(ssh).location")`

2021-11-24 13:53 UTC, dagguh commented on CHANGELOG.md
> +## [4.19.0] - 2021-11-25
This release doesn't exist yet and the date is speculated.
We should leave it under the `Unreleased` section, because that's true.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +data class JiraUserPassword(
Avoid Kotlin data classes in the API. They're impossible to evolve.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +            logger.info("Password not provided, skipping dataset update")
What is the point of an `JiraUserPasswordOverridingDatabase` instance, which doesn't actually override the password?

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +@Deprecated(message = "Pass licenses as Files to reduce accidental leakage of the license")
We shouldn't add API, which is immediately deprecated.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    username = "admin",
This can be a default in the `JiraUserPasswordOverridingDatabase.Builder`, so then we can get rid of this extension.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +                sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='${userPassword.encrypted}' WHERE user_name='$username';")
Why is `$cwdUserTableName` a variable, but `cwd_directory_attribute` a constant?

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        val dbNamePrefix = if (cwdUserTableName.contains(".")) cwdUserTableName.substringBefore(".") + "." else ""
Instead of reverse-engineering the prefix, it's be easier to use and maintain if it was just an explicit parameter.

2021-11-24 13:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +    companion object {
This exposes a new public API: `LicenseOverridingMysql.Companion`. We can make it private. Or we can let the logger be instance-local.

2021-11-24 16:45 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +data class JiraUserPassword(
I will change it. Could you give an example?

2021-11-24 16:50 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +    companion object {
making it private has no effect until kotlin 1.4 :/
https://youtrack.jetbrains.com/issue/KT-11567

Is that why there are no companion objects for loggers in this project? (like private static logger in java initialized once)

2021-11-24 16:54 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    username = "admin",
This extensions is to easily add this decorator in jpt, I don't think it can be done as easy to read as with extension
```
fun Dataset.withAdminPassword(adminPassword: JiraUserPassword): Dataset {
    return Dataset.Builder(this)
        .database(this.database.withAdminPassword(adminPassword))
        .build()
}
```
and usage
```
    private val adminPassword = getAdminPassword()

    private val dataset = DatasetRegistry.getDataset(
        format = DatasetFormat.EIGHT,
        name = DatasetName.ENTERPRISE_UNIMODAL
    ).withAdminPassword(adminPassword)
```

2021-11-24 16:57 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +                sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='${userPassword.encrypted}' WHERE user_name='$username';")
Makes sense to remove table name parameters if there is no reason to keep it. @pczuj do you remember why you made it as a parameter?

2021-11-24 16:59 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +            logger.info("Password not provided, skipping dataset update")
It was initially used in DatasetRegistry in jpt to avoid excessive if statements in the code. But now it has been move out of DatasetRegistry so not needed anymore

2021-11-25 08:14 UTC, pczuj reviewed
oh... github has this option that makes your comments invisible... cool option. I was wondering why my messages are ignored. Had to click "finish your review"

2021-11-25 08:14 UTC, pczuj commented on CHANGELOG.md
BTW I'm not yet sure if we shoudl reuse the issue key as it's an internal one. Maybe we want to create a public facing clone.

2021-11-25 08:14 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    username = "admin",
I think that this kind of "wrapping as a function" API is fine to add. Kotlin stdlib seems to be using similar approach for stream operations on collections.

I agree though that we should move the `username = "admin",` to defaults of the builder and not have it here.

2021-11-25 08:35 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    val plainText: String,
Because:
- this class is used not only in infrastructure but also in JPT and both plain text + encrypted are needed there
- plain text or encrypted is needed for updating dataset. It depends on crowd configuration (user_encryption_method attribute in cwd_directory_attribute table)

2021-11-25 08:36 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        private var userPassword: JiraUserPassword?
It's not optional anymore. It made sense when it was used in DatasetRegistry, but it's no longer there so when you use this decorator you definitely want to have a password to be changed

2021-11-25 09:12 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +        private val logger: Logger = LogManager.getLogger(LicenseOverridingMysql::class.java)
I don't think we are using static loggers anywhere else (or at least in majority places it is just a class field). Possibly we should follow single approach and I'd suggest to use a field - it probably has _some_ performance overhead on object initialisation, but it also has less boilerplate.

2021-11-25 09:46 UTC, mgrzaslewicz commented on CHANGELOG.md
All previous JPERF links were pointing to ecosystem too. It doesn't mean this one should follow. 
By public which address do you mean?

2021-11-25 10:16 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        if (shouldUseEncryption(ssh)) {
#### Suggestion
(Disclaimer: I understand that the way this class is implemented is a norm that we are following in Atlassian, so I'm not insisting of any change here. It's just a suggestion)

The original version of the `JiraUserPasswordOverridingDatabase` had single responsibility - to update a database entry with given value. It didn't even know what the table name is (ok there was a default, but the idea was that this is not the class responsibility)

Now the class not only has the table name knowledge, but also does some decisions around encryption method.

My suggestion would be to split this into multiple wrappers, where one of them would be the dumb one that just does the update. You can also crate another wrapper which would be a given structure of wrappers initialized at once with single constructor.

2021-11-25 10:33 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +            logger.info("Updating credential with encrypted password")
Note: The convention in JPT is that INFO log is for the regular user, so that it appears in console output (DEBUG is for power user and it's in file). It's expected that only the key events are logged as INFO.

Subjective: I'm fan of observability via composition. You can have dedicated implementations of wrappers which only responsibility is to do the logging. Here for such wrapper we would need to pass the description of executed query to the next layer, so that the logging wrapper could use that information. Maybe it'd be good to create a new interface for SqlClient which would include such information (as optional?).

2021-11-25 10:48 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +    private val logger: Logger = LogManager.getLogger(LicenseOverridingMysql::class.java)
Forgot to restore it when removed companion object

2021-11-25 10:52 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        if (shouldUseEncryption(ssh)) {
Maybe I don't understand who the consumers of the library might be.
I thought it's for JPT and provisioning Jira - which means table names are constant.
Where else might this class be used?

2021-11-25 11:08 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +    private val logger: Logger = LogManager.getLogger(LicenseOverridingMysql::class.java)
BTW in the past we had situations where incorrect class was used for logger. This is why we switched to `this::class.java`: https://stash.atlassian.com/projects/JIRASERVER/repos/jira-performance-tests/commits/0abc9352ac35db7ea853c50da5fea48f3bc8f90a#src/test/kotlin/com/atlassian/jira/test/performance/infrastructure/MySqlDatabase.kt

2021-11-25 11:19 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        if (shouldUseEncryption(ssh)) {
The logic is fine. What my suggestion is about is the code structure. 

It may be subjective, but I find more granular classes with as limited responsibilities as possible easier to grasp. Such modular approach with the usage of composition can help with the future refactoring, as you may for example be interested in inserting logic between the decision around `shouldUseEncryption` and the actual SQL operation. If we continue to add such logic into a single class we will end up with Jira's "Manager" problem, where all logic is in a single class and it's easy to get lost.

In general it's IMHO good idea to promote [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle). Frequently new devs who start working on projects are mostly copying patterns existing in the project. Even if the decomposition wouldn't have much practical value directly in our case it would still be worth to do it just for pattern promotion.

2021-11-25 11:22 UTC, pczuj commented on CHANGELOG.md
EAN (ecosystem.atlassian.net) is a public instance. JPERF-729 is on EAN, but it's an internal restricted issue right now. We could open it after releasing the fix, however I'm not sure if we are able to do that.

2021-11-25 12:22 UTC, mgrzaslewicz commented on CHANGELOG.md
![image](https://user-images.githubusercontent.com/5358084/143440973-2a875bb4-33df-410a-9744-df6532168fd5.png)
It seems that can be changed easily (well, I didn't click it but I suppose it wouldn't show up if clicking would result in permission failure)

2021-11-25 12:30 UTC, pczuj commented on CHANGELOG.md
Yes, technically that can be done. I was more concerned about it from the process perspective.

2021-11-25 12:43 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +                sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='${userPassword.encrypted}' WHERE user_name='$username';")
The reason was to split the responsibility from a class that knows only the structure of table, but doesn't know it's name. It was also to allow overwrites in case the table name changes in the future or is incorrect for some DBs. We are relying on something that is not really an Jira API here.

We could make the fields also configurable for better portability, but then the class will have nothing specific about Jira DB.

2021-11-25 15:53 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +    fun getEncryptedPassword(ssh: SshConnection): String
I think we shouldn't have `SshConnection` as an argument for this interface, the ssh is an implementation detail.

If you want to have an interface that is looking for an `SshConnection` I'd suggest to make it a `SshBasedPasswordEncrypterFactory` with `createEncrypter(ssh: SshConnection)` method or something like that.

2021-11-25 15:55 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +    fun getEncryptedPassword(ssh: SshConnection): String
you can also expect lambda `(SshConnection) -> JiraUserPasswordEncryptor` where encrypter's method would be `getEncryptedPassword(password: String)`

2021-11-25 18:04 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val jiraUserPasswordEncryptor: JiraUserPasswordEncryptor
I think this is better now, however I decided to spend some time to show how I'd see the implementation of this mechanism with the current requirements
https://github.com/atlassian/infrastructure/blob/a138b085a9d9acc573a573510d532ada3da13c3a/src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraDatabaseReconfigurator.kt

Feel free to ignore it though if you feel like it has no value.

2021-11-25 18:05 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
This part of doc should probably be adjusted, as the provided password is in plain text and the encryption mechanism is planned to be added.

2021-11-29 10:40 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +data class JiraUserPassword(
We can just remove the `data` keyword.

2021-11-29 10:42 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +    companion object {
Oh, didn't know that.
The `companion` wasn't used, because we didn't believe that introducing static stuff is necessary. In principle, the logger could be even injectable via builder (with a default).

2021-11-29 10:46 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    username = "admin",
We can add a copying constructor for builder, e.g. [like this](https://github.com/atlassian/virtual-users/blob/release-3.13.0/src/main/kotlin/com/atlassian/performance/tools/virtualusers/api/config/VirtualUserBehavior.kt#L152-L154).
PS. The `username` default can still be put into the builder either way.

2021-11-29 10:49 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +    username = "admin",
PS. the return type should be `Dataset`

2021-11-29 10:50 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +                sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='${userPassword.encrypted}' WHERE user_name='$username';")
Then why isn't `cwd_directory_attribute` also parametrized? YAGNI TBH.

2021-11-29 11:03 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt
> +        private val logger: Logger = LogManager.getLogger(LicenseOverridingMysql::class.java)
Also, premature optimization :wink:

2021-11-29 11:07 UTC, dagguh commented on CHANGELOG.md
We should link the issue even if it's internal. We should/could have a process for revealing the security issues after some time after release.

2021-11-29 11:11 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +        if (shouldUseEncryption(ssh)) {
The update/encrypt responsibility split makes sense. Maybe it would even obsolesce the `JiraUserPassword` type.

2021-11-29 11:13 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +            logger.info("Updating credential with encrypted password")
True. The "key events" tend to be things that show high level progress or simply long-running processes, like: provisioning Jira, applying load, gathering results.

2021-11-29 11:15 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +    fun getEncryptedPassword(ssh: SshConnection): String
`SshBasedPasswordEncrypterFactory` -> `SshEncrypterFactory`. They can encrypt any text, not just passwords.

2021-11-29 11:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +                logger.warn("Unknown user_encryption_method. Assuming encrypted password should be used")
Is it supposed to cover cases when it is missing too?

2021-11-29 11:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +            sqlResult.contains("atlassian-security") -> true
So `atlassian-security` will work with any `passwordEncryptFunction: (String) -> String`?

2021-11-29 11:24 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +internal class DefaultJiraUserPasswordEncryptor(
If it's `internal`, then it shouldn't be in API package.
It also means that the only offered `JiraUserPasswordEncryptor` impl cannot be used, so every client would have to implement their own.
PS. what are the use cases for different `JiraUserPasswordEncryptor`s?

2021-11-29 11:26 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
I hope the `atlassian-crowd:4.2.2` dependency tree isn't insane :crossed_fingers:
If it is, maybe they have a smaller submodule with the functionality?

2021-11-29 11:32 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/JiraUserPasswordOverridingDatabase.kt
> +                sqlClient.runSql(ssh, "UPDATE $cwdUserTableName SET credential='${userPassword.encrypted}' WHERE user_name='$username';")
I think it's because the table name parameter was made by me with first version of the code was created. Then @mgrzaslewicz took over the PR and his addition didn't follow the same approach. That's where the 2 parts of the code differ.

I don't think YAGNI applies here. As mentioned in my previous comment there are at least 2 reasons for the delegation of table name definition (responsibility split + uncertain contract). Both of those are essentially preparing for easier modification, e.g. it would be easier to adapt the table name from the lib consumer repository rather than relying on a new release.

I'd promote a quite from Matrin Fowler here: https://www.martinfowler.com/bliki/Yagni.html

> Yagni only applies to capabilities built into the software to support a presumptive feature, it does not apply to effort to make the software easier to modify.

2021-11-29 14:51 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> + * To encode the password use [com.atlassian.crowd.password.encoder.AtlassianSecurityPasswordEncoder](https://docs.atlassian.com/atlassian-crowd/4.2.2/com/atlassian/crowd/password/encoder/AtlassianSe
I thought we decided not to include this dependency in the infrastructure library. I've adjusted documentation

2021-11-29 14:52 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +                logger.warn("Unknown user_encryption_method. Assuming encrypted password should be used")
I decided to change that and treat that as an error

2021-11-29 14:53 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +            sqlResult.contains("atlassian-security") -> true
no, but I don't want this library to depend on atlassian-security. Or maybe we should include it?

2021-11-29 14:54 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val jiraUserPasswordEncryptor: JiraUserPasswordEncryptor
I found your implementation a bit too complicated and provided something hopefully easier to understand

2022-01-11 08:22 UTC, dagguh requested changes

2022-01-11 08:22 UTC, dagguh commented on .gitignore
> +.idea
Pro-tip: you can exclude your personal environment files via [global git ignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer)

2022-01-11 08:22 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +class DefaultJiraUserPasswordEncryptorProvider(passwordEncryptFunction: (String) -> String) : JiraUserPasswordEncryptorProvider {
`DefaultJiraUserPasswordEncryptorProvider` and `DefaultJiraUserPasswordEncryptionTypeService` are very enterprisey. No need to overengineer this, it's just a simple polymorphism with two variants: plain and encrypted. We can do it with one interface and two impls. Especially in the API.

2022-01-11 08:22 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
This is an alias on the builder, which provides some extra defaults. Let's just put those defaults into the builder.

2022-01-11 08:22 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +    private val passwordEncryptFunction: (String) -> String
We shouldn't put Kotlin functino types into the API, because this one is `kotlin.jvm.functions.Function1`, which is clumsy to use from Java. A `java.util.function.Function<String, String>` would do just fine (if we even need anonymous types).

2022-01-11 08:24 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabase.kt
> +        private val logger: Logger = LogManager.getLogger(MySqlDatabase::class.java)
Why bother changing this?

2022-01-11 08:27 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +            sqlResult.contains("atlassian-security") -> true
I see. Ok, we can leave the burden of finding the proper function on the consumer for now. We'll see how it goes.

2022-01-11 08:38 UTC, mgrzaslewicz commented on .gitignore
> +.idea
Good tip. I'd keep it anyway, relying on personal settings doesn't solve the problem for everyone

2022-01-11 08:40 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
I'd keep this as it's very convenient in JPT to use it. And it's used in dozens of places
e.g.
```
 private val experimentDataset = PortfolioDataSetProvider
        .forJiraVersion(testConfig.experimentJiraVersion)
        .withAdminPassword(testConfig.adminPasswordPlainText)
```

2022-01-11 08:44 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabase.kt
> +        private val logger: Logger = LogManager.getLogger(MySqlDatabase::class.java)
I made several similar changes (to have static logger init instead of per instance) and then reverted them based on comments in this pull request. This one is a leftover, will revert it

2022-01-11 10:37 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
I see. We can preserve the convenience without duplicating sources of defaults:
```kotlin
 private val experimentDataset = PortfolioDataSetProvider.forJiraVersion(testConfig.experimentJiraVersion)
        .overrideAdmin()  // returns JiraUserPasswordOverridingDatabase.Builder
        .passwordPlainText(testConfig.adminPasswordPlainText)
        // .sqlClient(...)
        // .jiraDatabaseSchemaName()
        .build()
```

2022-01-11 11:32 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> +class DefaultJiraUserPasswordEncryptorProvider(
`Default` doesn't convey the behavior of the implementation (or how it could differ from other possible impls).
This one adapts to `cwd_directory_attribute`, so it could be called `CrowdAdaptiveEncryptorProvider`.

PS. We could drop the "provider" abstraction and make it a `CrowdAdaptiveEncryptor : JiraUserPasswordEncryptor`, delegating to the chosen impl.

2022-01-11 11:32 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordEncryptor.kt
> -enum class JiraUserPasswordEncryptionType {
Nice :smile: bye bye enum :wave:

2022-01-11 13:28 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
Still looks more complicated than one line ``.withAdminPassword(testConfig.adminPasswordPlainText)`` and multiple that by all usages - you have more code to maintain

2022-01-11 13:32 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
It's less code to maintain. See [the diff](https://github.com/pczuj/infrastructure/pull/1/commits/e09bc48692a6679856d32faa393efed40421e914), more red lines than green ones.

2022-01-11 13:33 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.withAdminPassword(adminPasswordPlainText: String, passwordEncryptFunction: (String) -> String): Database {
And it's not more complicated, it gives you one way to pass a given param, instead of multiple ways. Note that the `//` commented lines are not necessary, but they're *possible* now (unlike before).

2022-01-11 13:33 UTC, dagguh commented
Here's a PR with some of my suggestions: https://github.com/pczuj/infrastructure/pull/1

2022-01-11 15:41 UTC, dagguh submitted a review, later dismissed

2022-01-12 09:32 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
Would it make sense to move this `CrowdEncryptedPasswordProvider` to separate file?

2022-01-12 09:58 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
done

2022-01-12 11:23 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
I believe `String#contains` on the SQL query output is not the correct contract for choosing the password encryption. It may be good enough simplification, however I'd suggest to be honest about this hack in the code.

Also in the idea of [SOLID](https://en.wikipedia.org/wiki/SOLID) I'd personally split this class into smaller modules:
 * `SshSqlQueryOutputProvider(sqlClient: SshSqlClient, sqlQueryProvider: () -> String) : (ssh: SshConnection) -> String`
 * `JiraDirectoryAttributeSqlQueryProvider(schema: String, attribute_name: String): () -> String`
 * `JiraDirectoryAttributeSqlQueryOutputParser() : (String) -> List<DirectoryAttribute>`
 * `JiraDirectoryAttributePicker(directoryId: String) : (List<DirectoryAttribute>) -> DirectoryAttribute`
 * `JiraDirectoryAttribute { val directoryId: String, val name: String, val value: String }`
 * `JiraDirectoryAttributeBasedPasswordPicker(passwordMapping: Map<String, String>, defaultHandler: () -> String): (DirectoryAttribute) -> String`

Glueing this together can be done in different ways. The idea is to represent every behavior as class for better modularity. Ideally we could allow every module to be overridable, however the example below doesn't do that.

```
SshSqlQueryExecutor<T>(
    sqlQueryOutputProvider: (ssh: SshConnection) -> String,
    sqlQueryOutputTransformer: (String) -> T
) : (ssh: SshConnection) -> T
```

```
fun <I, T, O> ((I) -> T).map(transformation: (T) -> O) = { input: I -> transformation(this(input)) }
```

```
CrowdEncryptedPasswordProvider(
    sqlClient: SshSqlClient,
    jiraDatabaseSchemaName: String,
    passwordPlainText: String,
    passwordEncryptedWithAtlassianSecurityPasswordEncoder: String
) : (ssh: SshConnection) -> String by SshSqlQueryExecutor(
    sqlQueryOutputProvider = SshSqlQueryOutputProvider(
        sqlClient = sqlClient,
        sqlQueryProvider = JiraDirectoryAttributeSqlQueryProvider(
            schema = jiraDatabaseSchemaName,
            attribute_name = "user_encryption_method"
        )
    )
    sqlQueryOutputTransformer = JiraDirectoryAttributeSqlQueryOutputParser()
        .map(JiraDirectoryAttributePicker("1"))
        .map(
            JiraDirectoryAttributeBasedPasswordPicker(
                passwordMapping = listOf(
                    "plaintext" to passwordPlainText
                    "atlassian-security" to passwordEncryptedWithAtlassianSecurityPasswordEncoder
                ),
                defaultHandler = { throw RuntimeException("Unknown jira user password encryption type") }
            )
        )
)
```
 
Decide yourself it such change could be better or now.

2022-01-12 11:28 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
We can generate infinite abstractions. The question is: "which ones are useful?". Each abstraction should have a practical (not purely hypothetical) purpose.

2022-01-12 11:38 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
IMHO this is overcomplicating simple job and premature optimization. The example provided is hard to understand, at least for me.
Even extracting JiraUserEncryptedPasswordProvider from JiraUserPasswordOverridingDatabase has some drawback and does not make code easier to understand.
It is already overridable, if someone wants to provide own implementation of password provider one can do it easily.

String result from db contains also some additional lines including header. You can prepare here super precise implementation and do not use String.contains. But what would be the benefit?
Library providing crowd encryption there are 2 enums. If that changes, any implementation will have to be changed.

2022-01-12 11:57 UTC, pczuj commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
Rant / Topic not specific to the PR, but still related to the changes:

I find it somewhat risky to use the industry standard ways of junit test setup. It promotes practices of hiding what is actually happening as part of the code execution. I know that follwoing industry standard reduced WTF/min, however what if the standard itself is incorrect?

An alternative way would be to wrap the test class state into an inner class of the test and return this test state as part of `setup()` factory method. It would cost a single line in each test, however there would be no doubt what the execution order is and there would be no usage of `lateinit var`, so there is less chance that new contributors will repeat it in other places of the code now knowing that we are trying to avoid mutability and inexplicit nullability.

Actionable around it is not required, however I'd like to know you thoughts on that.

2022-01-12 12:07 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val logger: Logger = LogManager.getLogger(this::class.java)
Nit: Logging responsibility could be split to a decorator on this class.

2022-01-12 12:08 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val logger: Logger = LogManager.getLogger(this::class.java)
What would be the benefit?

2022-01-12 12:10 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
It's about deduplicating setup code, bit more complex to read, but less to read.

2022-01-12 12:22 UTC, mgrzaslewicz commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
I've checked 'feelings' around below implementation and the benefit seem to be tiny.
Anyway, I think it might be worth implementing. 
```
class JiraUserPasswordOverridingDatabaseTest {

    private val jira = URI("http://localhost/")
    private val samplePlainTextPassword = "plain text password"
    private val expectedEncryptedPassword = "*******"

    data class TestContext(
        val database: Database,
        val underlyingDatabase: RememberingDatabase,
        val sshConnection: RememberingSshConnection,
        val sqlClient: MockSshSqlClient
    )

    private lateinit var testContext: TestContext

    @Before
    fun setup() {
        val db = RememberingDatabase()
        val sqlClient = MockSshSqlClient()
        testContext = TestContext(
            underlyingDatabase = db,
            sshConnection = RememberingSshConnection(),
            sqlClient = sqlClient,
            database = db
                .overrideAdminPassword(
                    adminPasswordPlainText = samplePlainTextPassword,
                    adminPasswordEncrypted = expectedEncryptedPassword
                )
                .sqlClient(sqlClient)
                .schema("jira")
                .jiraUserEncryptedPasswordProvider(object : JiraUserEncryptedPasswordProvider {
                    override fun getEncryptedPassword(ssh: SshConnection) = expectedEncryptedPassword
                })
                .build()
        )
    }

    @Test
    fun shouldSetupUnderlyingDatabase() {
        // when
        testContext.database.setup(testContext.sshConnection)
        testContext.database.start(jira, testContext.sshConnection)
        // then
        assertThat(testContext.underlyingDatabase.isSetup).`as`("underlying database setup").isTrue()
    }
}
```

2022-01-12 12:24 UTC, mgrzaslewicz commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
or this way:
```
    @Test
    fun shouldSetupUnderlyingDatabase() {
        with(testContext) {
            // when
            database.setup(sshConnection)
            database.start(jira, sshConnection)
            // then
            assertThat(underlyingDatabase.isSetup).`as`("underlying database setup").isTrue()
        }
    }
```
but both feels weird, maybe because I've never seen nor used such way to implement test just to avoid lateinit var

2022-01-12 12:32 UTC, mgrzaslewicz commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
So you mean something like that, which requires no knowledge about any magic done by adding @Before annotation
```
class JiraUserPasswordOverridingDatabaseTest {

    private val jira = URI("http://localhost/")
    private val samplePlainTextPassword = "plain text password"
    private val expectedEncryptedPassword = "*******"

    data class TestContext(
        val database: Database,
        val underlyingDatabase: RememberingDatabase,
        val sshConnection: RememberingSshConnection,
        val sqlClient: MockSshSqlClient
    )

    fun setup(): TestContext {
        val db = RememberingDatabase()
        val sqlClient = MockSshSqlClient()
        return TestContext(
            underlyingDatabase = db,
            sshConnection = RememberingSshConnection(),
            sqlClient = sqlClient,
            database = db
                .overrideAdminPassword(
                    adminPasswordPlainText = samplePlainTextPassword,
                    adminPasswordEncrypted = expectedEncryptedPassword
                )
                .sqlClient(sqlClient)
                .schema("jira")
                .jiraUserEncryptedPasswordProvider(object : JiraUserEncryptedPasswordProvider {
                    override fun getEncryptedPassword(ssh: SshConnection) = expectedEncryptedPassword
                })
                .build()
        )
    }

    @Test
    fun shouldSetupUnderlyingDatabase() {
        val testContext = setup()
        with(testContext) {
            // when
            database.setup(sshConnection)
            database.start(jira, sshConnection)
            // then
            assertThat(underlyingDatabase.isSetup).`as`("underlying database setup").isTrue()
        }
    }
}
```

2022-01-12 15:14 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserEncryptedPasswordProvider.kt
> +class CrowdEncryptedPasswordProvider(
> We can generate infinite abstractions. 

I'm not pointing abstractions here. There is limited number of responsibilities and this class has more than one. At least query execution and excetional result condition handling IMHO should be split.

If we are assuming a contract that is not given to us explicitly I'd prefer to have this contract isolated as much as possible. In our case we are assuming that:
 * The query will return only one entry or the first entry returned will be the one that we are interested in - In the example code I added explicit picker for the entry that we are interested in. We could implement it as "take the first one" and document it as a hack. There are also other ways to implement it more explicitly.
 * The query will return header not containing the "plaintext" or "atlassian-security" - In the example code  I added parser for SQL output. This one also may be a hack that checks exactly for `String#contains` and maps it e.g. to an enum class. Such class again would allow us to say in javadoc that it's a hack to reduce cost of the implementation.

> IMHO this is overcomplicating simple job and premature optimization.

Ability to split it to many responsibilities proves that this is not so simple and fact that I'm able to use this way to spot some implicit contracts that the code starts to rely on makes it not premature optimization, but rather quality assurance. 

Still I'm not insisting in chaging it if both of you don't see value in it. So far my understanding of SRP was that we should split as much as possible and that SRP is something that we are following. Possibly one of those is incorrect.

2022-01-12 15:41 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val logger: Logger = LogManager.getLogger(this::class.java)
There are multiple benefits:
 * Decoupling logging from a class ensures that your code is observable
     * It's possible to create code that will replace logging with something easier to understand by machine, e.g. event system.
     * It's possible to write unit tests on the same signals as would trigger log lines seen by the user, i.e. you don't need to mock logger to use same signals.
 * You could easily remove the logger code from the execution path by removing the decorator from the initialisation. It could be done dynamically.
 * You could unit test the logger responsibility.
 * It spreads the foundation of the good practice of keeping things SRP.

Again I'm not insisting, especially with this one, because our practice was so far to not decouple logger from other  business logic. Still I wanted to point it out to see your thoughts on it. I personally would prefer us to follow the decoupling practices, because I see how not following it damages the flexibility of our implementations. I don't believe in popular thinking that everything can be rewritten to match the new requirements - from my experience it never happens. However we can write code that is modular and later one be able to initialise it differently to achieve new requirements.

2022-01-12 15:52 UTC, pczuj commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabaseTest.kt
> +    private lateinit var sqlClient: MockSshSqlClient
Yes @mgrzaslewicz exactly that. The junit magic seems to be unnecessary for me.

 Not sure if we should follow this practice in this PR though. Maybe the risk that someone new will come and do it with `@Setup` anyway is the reason to not go for it. I think that having 2 ways in the code may be worse then having only the worse version of the solution. Possibly a separate PR that changes every occurance of `@Setup` to something like this would be correct way.

2022-01-12 17:35 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val logger: Logger = LogManager.getLogger(this::class.java)
I understand all the benefits, but do we really need them?
Was there a single time in this library we had to test what's being logged or a need to make it configurable?

2022-01-13 08:14 UTC, dagguh approved these changes

2022-01-13 08:14 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +fun Database.overrideAdminPassword(adminPasswordPlainText: String, adminPasswordEncrypted: String): JiraUserPasswordOverridingDatabase.Builder {
Passing the builder opens up ways to override other params, thanks :+1:

2022-01-13 08:34 UTC, merged

2022-01-13 08:53 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/passwordoverride/JiraUserPasswordOverridingDatabase.kt
> +    private val logger: Logger = LogManager.getLogger(this::class.java)
@pczuj I think these are interesting dev experiments, they deserve to be explored. However, we shouldn't mix them inside a big and overdue feature PR.