JPERF-838: Add Splunkforwarder.jsonifyLog4j method for Log4j1 and Log4j2
atlassian/infrastructure pull request #119
Opened 2022-10-18 10:44 UTC by filip-nowak-atl

Jsonify both log4j 1 and log4j 2 config files

2022-10-18 11:33 UTC, dagguh requested changes

2022-10-18 11:33 UTC, dagguh commented on CHANGELOG.md
> +- Added `jsonifyLog4j(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String)` to `SplunkForwarder` to enable jsonifying log4j2 configurations. [JPERF-838]
```suggestion
- Enable jsonifying log4j2 configurations in `SplunkForwarder`. Resolve [JPERF-838].

[JPERF-838] https://ecosystem.atlassian.net/browse/JPERF-838
```

2022-10-18 11:33 UTC, dagguh commented on build.gradle.kts
> +                "org.seleniumhq.selenium:selenium-chrome-driver" -> useVersion("3.11.0")
Why?

2022-10-18 11:33 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4jJsonifierTest.kt
> +    private var mockConnection: SshConnection = Mockito.mock(SshConnection::class.java)
We avoid Mockito and all reflection, auto-magic, hard-to-debug libs. Perhaps you can reuse `RememberingSshConnection`?

2022-10-18 11:33 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4jJsonifier.kt
> +package com.atlassian.performance.tools.infrastructure.api.splunk
Let's not leak it to the API:
```suggestion
package com.atlassian.performance.tools.infrastructure.splunk
```

2022-10-18 11:33 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +    fun jsonifyLog4j(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String)
Existing `SplunkForwarder` implementations will stop compiling. We maintain source compatibility and this is breaking it.
So we should find a different solution or release a major version.

2022-10-18 11:33 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +    fun jsonifyLog4j(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String)
Perhaps we can go for a decorator around `SplunkForwarder`:
```kotlin
class Log4j2SplunkForwarder(
    private val delegate: Log4j2SplunkForwarder
) : SplunkForwarder by delegate {

    override fun jsonifyLog4j(sshConnection: SshConnection, log4jPropertiesPath: String) {
        // ...
    }
}
```

2022-10-18 11:33 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4jJsonifierTest.kt
> +internal class Log4jJsonifierTest {
TBH this doesn't test much. Everything is mocked so this test suite basically reimplements the `Log4jJsonifier`.

2022-10-18 11:33 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4jJsonifierTest.kt
> +internal class Log4jJsonifierTest {
Unfortunately infra doesn't have a nice integration test (yet, [incoming](https://github.com/atlassian/infrastructure/pull/103/files#diff-157e10769bd024cfba0f5672d6cf07ba57216d2fec8a8939e3c7ca466643e2beR41)). But I'd rather leave this untested right now.

2022-10-18 11:40 UTC, filip-nowak-atl commented on build.gradle.kts
> +                "org.seleniumhq.selenium:selenium-chrome-driver" -> useVersion("3.11.0")
Good question, gradle detected conflicts and refused to build anything.

2022-10-18 11:43 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +    fun jsonifyLog4j(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String)
Maybe empty default implementation?

2022-10-18 11:44 UTC, filip-nowak-atl commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4jJsonifierTest.kt
> +internal class Log4jJsonifierTest {
I can remove the test - this way we'll most likely avoid the fun with dependencies.

2022-10-18 11:59 UTC, dagguh commented on build.gradle.kts
> +                "org.seleniumhq.selenium:selenium-chrome-driver" -> useVersion("3.11.0")
Ah got it, you wanted to add Mockito dependency, but rewriting all locks tried to bump other deps too and conflicts were detected. You can [update the locks selectively](https://docs.gradle.org/current/userguide/dependency_locking.html#selectively_updating_lock_state_entries) to avoid those bumps.

2022-10-18 13:21 UTC, mgrzaslewicz commented on .gitignore
> +.DS_Store
I've seen similar comment many times in various pull requests. It means many people don't have such file and it might help to have it in .gitignore per project

2022-10-18 13:32 UTC, dagguh commented on .gitignore
> +.DS_Store
I always imagined all projects in the world having to list all possible OS- and IDE-generated files: Windows, macOS, Notepad++, IntelliJ, VS Code, Visual Studio, Emacs, etc. etc. And it felt wrong.
But I guess you're right. If we follow the path of least resistance, we'll get the most frequent cases out of the way (macOS + IntelliJ).
OTOH there's a bunch of PR feedback that's repeated, like changelog or keeping compatibility. Perhaps we could use [PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) for that.

2022-10-18 14:44 UTC, dagguh requested changes

2022-10-18 14:44 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +// Extension method to avoid breaking changes
[Extension methods](https://kotlinlang.org/docs/java-to-kotlin-interop.html#package-level-functions) in API look funky in Java as a static: `SplunkForwarderKt.jsonifyLog4j1AndLog4j2()`.
You can achieve the same goal by [default methods](https://kotlinlang.org/docs/java-to-kotlin-interop.html#default-methods-in-interfaces), we've got `-Xjvm-default` already enabled.

2022-10-18 14:44 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +fun SplunkForwarder.jsonifyLog4j1AndLog4j2(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String) {
Have you tried a [decorator](https://github.com/atlassian/infrastructure/pull/119#discussion_r998080974)?

If you're worried you'd have to hunt down all places where `SplunkForwarder` is created, then don't worry. Because if you planned to call this `jsonifyLog4j1AndLog4j2` in place of [the existing call in `StandaloneNodeFormula`](https://github.com/atlassian/aws-infrastructure/blob/release-2.25.8/src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/jira/StandaloneNodeFormula.kt#L88), then you might as well use the decorator there. But it gets better, you can apply the decorator right here [in `JiraNoceConfig.Builder.build`](https://github.com/atlassian/infrastructure/blob/release-4.19.3/src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/JiraNodeConfig.kt#L146).

This assumes that the decorator can work with the `sshConnection: SshConnection, log4jPropertiesPath: String`, which are already passed. But that's enough already right? It can infer the `log4j2ConfigPath` with something like this:
```kotlin
val log4j2 = log4jPropertiesPath.replace("log4j.properties", "log4j2.properties")
```
With that the decorator should have all the information to handle both versions. At this point, it could be even done directly in existing impls: `AtlassianSplunkForwarder` and `UniversalSplunkForwarder` (via `Log4Jsonifier`), so not even the decorator would be necessary. It'd be an entirely transparent fix with no new API at all.

2022-10-19 06:37 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +fun SplunkForwarder.jsonifyLog4j1AndLog4j2(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String) {
Not yet, but when I think about it:
The problem with decorator is that it has no possiblity to pass the log4j 2 config filename, the solution to this problem is kind of 'hardcoding' for Jira, where it would be `log4j2.xml` as you propose. I'll try to rewrite this solution to use the decorator pattern though :) OR, just pass the log4j2 config filename via decorators constructor 🤔

2022-10-19 08:46 UTC, dagguh approved these changes

2022-10-19 08:46 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/JiraNodeConfig.kt
> +        splunkForwarder = Log4j2SplunkForwarder("log4j2.xml", splunkForwarder),
No need to maintain deprecated APIs. If somebody is still using them and suffering from the fix, they can just switch to non-deprecated API.

2022-10-19 08:46 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4j2SplunkForwarder.kt
> +        val log4j2ConfigPath = Paths.get(log4jPropertiesPath).resolveSibling(log4jConfigFileName).toString()
`resolveSibling` nice!

2022-10-19 09:00 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/SplunkForwarder.kt
> +fun SplunkForwarder.jsonifyLog4j1AndLog4j2(sshConnection: SshConnection, log4jPropertiesPath: String, log4j2ConfigPath: String) {
Fair point, it supports log4j2 xml config only anyway

2022-10-19 09:00 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/JiraNodeConfig.kt
> +        splunkForwarder = Log4j2SplunkForwarder("log4j2.xml", splunkForwarder),
Removed this change then

2022-10-19 09:07 UTC, dagguh approved these changes

2022-10-19 09:07 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/Sed.kt
> +    fun safeReplace(
Are those needed externally? If not, then we can make them `internal`.

2022-10-19 09:07 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/splunk/Log4jJsonifier.kt
> +            logger.info("Attempt to jsonify $log4jPropertiesPath was unsuccessful.")
FYI by default we print `INFO` to the console. Some tests run 10 benchmarks in parallel, each with 2x Jira DC, each with 2+ Jira nodes (and log4j configs). Perhaps all that info is not necessary for the tester? If we switch to `logger.debug`, they'll still be visible in the log files, but they won't be emitted to the console.

2022-10-19 09:14 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/splunk/Log4jJsonifier.kt
> +            logger.info("Attempt to jsonify $log4jPropertiesPath was unsuccessful.")
Done

2022-10-19 09:14 UTC, filip-nowak-atl commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/Sed.kt
> +    fun safeReplace(
Done

2022-10-19 09:20 UTC, dagguh approved these changes

2022-10-19 09:20 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/Log4j2SplunkForwarder.kt
> +class Log4j2SplunkForwarder(log4j2ConfigFileName: String, splunkForwarder: SplunkForwarder) :
This is new API and it's a good thing. It's a way to offer the fix to anyone, who's not going through the `JiraNodeConfig.Builder`. @atlassian/jpt, this will be a _minor_ release.

2022-10-19 09:29 UTC, merged

2022-10-19 13:04 UTC, pczuj commented
FYI I wasn't convinced that this change wasn't breaking module's API so I checked with [japicmp](https://siom79.github.io/japicmp/) and the report confirmed that minor release if correct ✅ 

Can't attach the report, because github rejects HTML attachements + chrome for some reason crashes when taking full page screenshot ¯\_(ツ)_/¯