JPERF-1457 Add monitoring VU host
atlassian/infrastructure pull request #178
Opened 2024-02-06 13:08 UTC by mgrzaslewicz

2024-02-06 13:19 UTC, dagguh requested changes

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    class Builder {
It's in an `internal class`, so not visible publicly anyway.

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +        fun build(): Pidstat = Pidstat(
```suggestion
        fun build(): Pidstat = OsMetric(
```

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +        fun params(pidstatParams: String): Builder = apply { this.pidstatParams = pidstatParams }
Consistency + context:
```suggestion
        fun params(params: String): Builder = apply { this.params = params }
```

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/virtualusers/SshVirtualUsers.kt
> +            monitoringProcesses.add(metric.start(ssh))
Let's `RemoteMonitoringProcess.stop` after the load.

2024-02-06 13:19 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/PidstatIT.kt
> +            .version("20.04")
```suggestion
```

2024-02-06 13:19 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
We'll need to parse the output sooner or later.
We can assert on more parsable parts, e.g. headers and timestamps. Are the timestamps local TZ? Will they be parsable if the timespan crosses midnight?

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/virtualusers/SshVirtualUsers.kt
> +        jdk.install(ssh)
This is for `VirtualUsersJar`, so they should be kept close together.

2024-02-06 13:19 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/PidstatIT.kt
> +class PidstatIT {
Thanks!

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +package com.atlassian.performance.tools.infrastructure
Consistent with other `OsMetric`s:
```suggestion
package com.atlassian.performance.tools.infrastructure.os
```

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    ): MonitoringProcess {
Consistent with other methods:
```suggestion
    override fun startMonitoring(connection: SshConnection): MonitoringProcess {
```

2024-02-06 13:19 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +        throw NotImplementedError("Use `start` method.")
Interesting approach to deprecated API. Let's see how it pans out

2024-02-06 13:21 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    class Builder {
Yes, but it will be easier later to make it public

2024-02-06 13:22 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +        fun build(): Pidstat = Pidstat(
I guess you mean `fun build(): OsMetrics = Pidstat(`

2024-02-06 13:26 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +        fun build(): Pidstat = Pidstat(
Yep, well spotted :)

2024-02-06 13:32 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    ): MonitoringProcess {
That's exactly how you make it inconsistent :)

2024-02-06 13:33 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
To see how it behaves, we can control the system clock, e.g.: `sudo date --set="2015-09-30 10:05:59.990"`. Dunno if `sudo hwclock --systohc` afterwards is necessary.

2024-02-06 13:34 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    ): MonitoringProcess {
WDYM? All other methods in this file don't chop single-param methods.

2024-02-06 13:36 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +package com.atlassian.performance.tools.infrastructure
Those are already spread out.
- `com.atlassian.performance.tools.infrastructure.api.os.Vmstat`
- `com.atlassian.performance.tools.infrastructure.Iostat`
I moved `Iostat` and `Pidstat` to `.os` as it seems to be a better fit.

2024-02-06 13:38 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +package com.atlassian.performance.tools.infrastructure
Ah right, thanks!

2024-02-06 13:41 UTC, dagguh approved these changes

2024-02-06 13:41 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/virtualusers/SshVirtualUsers.kt
> +                stopCollectingMetrics(ssh)
Ok so the metrics cover apply load + random stuff. It's more data, but it's less relevant (harder to interpret). If we stop immediately after applying load, then there's less post-processing to do.

2024-02-06 13:45 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
Snap, the move to `.os` cause GH to lose those comments. I'll repost them in new location.

2024-02-06 13:46 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
We'll need to parse the output sooner or later.
We can assert on more parsable parts, e.g. headers and timestamps. Are the timestamps local TZ? Will they be parsable if the timespan crosses midnight?

To see how it behaves, we can control the system clock, e.g.: sudo date --set="2015-09-30 10:05:59.990". Dunno if sudo hwclock --systohc afterwards is necessary.

2024-02-06 13:47 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +            .version("20.04")
The test doesn't seem to be 20.04-specific.
```suggestion
            .version("20.04")
```

2024-02-06 13:50 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Pidstat.kt
> +    ): MonitoringProcess {
I've changed `Iostat` and `Vmstat` to make all consistent to the rest of the project

2024-02-07 10:39 UTC, mgrzaslewicz commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
It's possible to create a chart based on the tuned output.
example:
![image](https://github.com/atlassian/infrastructure/assets/5358084/c23ef7c5-647d-423b-b8cd-7ee012917037)

2024-02-07 11:23 UTC, dagguh approved these changes

2024-02-07 11:23 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +                    ubuntu.install(ssh, listOf("firefox")) // to produce some CPU, RAM and disc usage
Noice 💪

2024-02-07 11:23 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/os/Pidstat.kt
> +         */
Thanks

2024-02-07 11:23 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/os/Pidstat.kt
> +        val process = ssh.startProcess("pidstat $params > $logPath 2>&1 > $logPath")
Right?
```suggestion
        val process = ssh.startProcess("pidstat $params 2>&1 > $logPath")
```

2024-02-07 11:23 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
The screenshot proves the output is parsable (by spreadsheets) and has useful data. So it's mergable IMHO.

We will need our own parser sooner or later. Do you think it's better to develop it with this devloop here or somewhere else? If the infra devloop is sufficient, it would make the API more useful (`List<ProcessMetrics>` instead of `File`). Also, it would allow changing the pidstat flags and updating the parser in one go.

- [ ] consider adding a parser

2024-02-07 11:34 UTC, mgrzaslewicz commented on src/test/kotlin/com/atlassian/performance/tools/infrastructure/os/PidstatIT.kt
> +                    assertThat(pidstatOutput).contains("CPU")
I'd vote for `let it happen to create manual chart 3 times` and after that create a parser. This will be the first one, JPT tests are just in progress with SNAPSHOT version of this lib

2024-02-07 12:10 UTC, dagguh approved these changes

2024-02-08 11:20 UTC, dagguh approved these changes

2024-02-08 11:20 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Docker.kt
> +     * https://forums.docker.com/t/etc-init-d-docker-62-ulimit-error-setting-limit-invalid-argument-problem/139424
Interesting, thanks for the context!
This changed `src/main` so it's affecting consumers. We should mention it in CHANGELOG

2024-02-08 11:20 UTC, merged

2024-02-08 11:50 UTC, mgrzaslewicz commented on src/main/kotlin/com/atlassian/performance/tools/infrastructure/Docker.kt
> +     * https://forums.docker.com/t/etc-init-d-docker-62-ulimit-error-setting-limit-invalid-argument-problem/139424
I'll mark it after release